---
title: "Pair-wise statistical comparison"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Pair-wise statistical comparison}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7,
  fig.height = 7,
  message = FALSE,
  warning = FALSE
)
```

# Libraries

```{r setup}
# library(regionaldrivers)
devtools::load_all()
library(magrittr)
```

# Data loading

`SSCT_data` and `SSCT_labelled_data` are loaded with the package.
Here is what 10 random rows of each looks like:

```{r data loading1, echo = FALSE}
SSCT_labelled_data %>% dplyr::sample_n(10) %>%
	knitr::kable(digits = 3, format = "html", caption = "SSCT_labelled_data") %>% 
	kableExtra::kable_styling(bootstrap_options = c("hover", "condensed")) %>% 
	kableExtra::scroll_box(width = "7in", height = "5in")
```

```{r data loading2, echo = FALSE}	
SSCT_data %>% dplyr::sample_n(10) %>%
	knitr::kable(digits = 3, format = "html", caption = "SSCT_data") %>% 
	kableExtra::kable_styling(bootstrap_options = c("hover", "condensed")) %>% 
	kableExtra::scroll_box(width = "7in", height = "5in")	
```

# Data transformation

We transform the data to retain what we need for the analysis:

```{r melting}
drivers_data <- cbind(SSCT_labelled_data, SSCT_data) %>%
	dplyr::select(c("SLOPE", "RUSLE", "ward"))	%>%
	dplyr::rename(ward.grp = ward) %>%
	reshape2::melt(id.vars = "ward.grp")
head(drivers_data)
```

# Statistical testing and visualization

We can now visualize the results from a pair-wise statistical comparison with `significative_diff_boxplot()`.

```{r viz box plots}
Dunn_results <- significative_diff_boxplot(drivers_data, type = "Dunn", padjmeth = "holm")
Dunn_results$p
```

```{r}
plotly::ggplotly(
	plot_pairwise_pvalue(Dunn_results$stats),
	tooltip = c("group1", "group2", "p.value")
)	
```